### ISSUE TITLE
why do you apply sqrt(d_model) in positional encoding and not in encoder block after attention?

### ISSUE THREAD

**Issue by EmmaRocheteau** [khirotaka/SAnD#3]
First of all thank you for sharing your code!

I noticed that you apply the math.sqrt(self.d_model) in the forward method of the positional encoding, but from what I can see that is only applied once via EncoderLayerForSAnD, but in the paper it indicates that this scaling should be applied for each attention layer?

I could definitely be misunderstanding!

**Comment by khirotaka** [comment]
Emma-san, Thank you for your interest in my code.

The reason I applied `sqrt(model)` in the `PE layer` is because I thought that the input vector `x` would be less than the `PE value` and if I added it as it was, it would be strongly affected by `PE`, so I wanted to adjust the magnitude.

> this scaling should be applied for each attention layer?

There should have been no specific description in the paper. Also, I believe that scaling is unnecessary in the attention layer. This is because there is no danger of it being overridden by other values.

**Comment by khirotaka** [comment]
> First of all thank you for sharing your code!
> 
> I noticed that you apply the math.sqrt(self.d_model) in the forward method of the positional encoding, but from what I can see that is only applied once via EncoderLayerForSAnD, but in the paper it indicates that this scaling should be applied for each attention layer?
> 
> I could definitely be misunderstanding!

**Comment by EmmaRocheteau** [comment]
oh right! that makes sense thank you! I've moved it to the EncoderLayerForSAnD class as I think it's more intuitive as relating to the embedding rather than the PositionalEncoding
