### ISSUE TITLE
PositionalEncoder

### ISSUE THREAD

**Issue by LuisMoralesAlonso** [khirotaka/SAnD#5]
In the paper they talk about: "The encoding is performed by mapping time step t to the same randomized lookup table during
both training and prediction."

In your code it seems more like using sinusoidal functions (and the one in the paper Attention is all You Need).

Is this Ok? Why not using then the randomized lookup solution?

**Comment by khirotaka** [comment]
Dear LuisMoralesAlonso-san

This implementation uses traditional Positional Encoding. This is because there was no detailed description of random lookup tables at all.  (at least at the time I did the implementation work).
So, as an alternative approach, I used the Transformer-style Positional Encoding.
After all, the goal is to teach the model the time difference information.


Please let me know if there are any additional explanations in the paper for creating random lookup tables, including the types and parameters of probability density functions.
Also, if you're implementing it, I'd be happy to send out a Pull Request.

**Comment by LuisMoralesAlonso** [comment]
it's ok, just wanted to confirm my suspect... just for your information, i'm trying to apply your implementation to financial time series, i'll come back with my results.
